//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthyMe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DietPlan
    {
        public int DietId { get; set; }
        public string DietName { get; set; }
        public string Accuracy { get; set; }
        public string Level { get; set; }
        public string DietDescription { get; set; }
        public string UserName { get; set; }
    }
}
