//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthyMe.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    
    public partial class Rating
    {
        public int RatingId { get; set; }
        public int Rating1 { get; set; }
        public int AppointmentId { get; set; }
        [Required]
        [AllowHtml]
        public string Comments { get; set; }
    
        public virtual Appointment Appointment { get; set; }
    }
}
